version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - run: |
          curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf api https://api.run.pivotal.io  # alternately target your private Cloud Foundry deployment
          cf auth "$CF_DEVUSER" "$CF_DEVPASSWORD"
          cf target -o fordvip -s development
          ls -al
          pwd
